### ISSUE TITLE
Unable to ingest data

### ISSUE THREAD

**Issue by sivanidwarampudi** [IBM/db2-event-store-clickstream#18]
Can you help me out with these errors?
![image](https://user-images.githubusercontent.com/50864528/91044506-03d17280-e633-11ea-9c92-e253b84f0e2f.png)
![image](https://user-images.githubusercontent.com/50864528/91044575-206daa80-e633-11ea-8dbc-5a2ff74f852e.png)

**Comment by markstur** [comment]
client could not connect to endpoint usually means you don't have the right IP address/port to access your eventstore

**Comment by sivanidwarampudi** [comment]
Thank you!
Nope there's no problem with ip,The issue is with docker resources in docker resources section we need to add path in file sharing and also in file explorer in the view option we need to choose hidden files in case of windows system.
And the issue is resolved.
