### ISSUE TITLE
Connecting db2-event-store to Cloud object storage

### ISSUE THREAD

**Issue by sivanidwarampudi** [IBM/db2-event-store-clickstream#19]
I completed successful ingestion of data to ibm-db2-event-store but was stuck at how to send this data to cloud object storage.Can you please help me out?
Thanks in advance!

**Comment by markstur** [comment]
This code pattern is about Db2 EventStore, there is no Cloud Object Storage.  For COS you should probably start here: https://cloud.ibm.com/docs/cloud-object-storage/getting-started.html#getting-started-console?cm_sp=Cloud-Product-_-OnPageNavLink-IBMCloudPlatform_IBMCloudObjectStorage-_-COS_GettingStarted
